# Generated by Django 4.0.5 on 2022-06-26 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_contato_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='datacriacao',
            new_name='data_criacao',
        ),
    ]
